### ISSUE TITLE
Please fix bugs related to map creator

### ISSUE THREAD

**Issue by nasuccc** [Regalis11/scpcb#246] opened 2023-03-27 21:00 UTC
BUG: room2_2 1048-A corruption
GAME IMPACT: High-Gamebreaking
FIX DIFFICULTY: Low (just removing the event) - High (fixing the event)
MAP CREATOR EXCLUSIVE: Possibly
DESCRIPTION: This bug happens in room2_2 (the giant fan room). When the room2_2 event is selected as "1048a" instead of "room2fan" strange things will start to happen. An example is a giant fan spawning inside the facility. There is a possibility this bug can cause the game to crash. 1048-A also appears to not spawn in the room.

BUG: 372 doesn't spawn
GAME IMPACT: Medium
FIX DIFFICULTY: Low-Medium
MAP CREATOR EXCLUSIVE: Yes
DESCRIPTION: 372 doesn't spawn in custom maps. When I tested it the event in the room it appears in (called "roompj") was set to 100%.

Other problems：https://undertowgames.com/forum/viewtopic.php?t=11044

**Comment by nasuccc** [comment] 2023-03-27 21:09
The text in the link is not edited by me, but I encountered these two bugs in the game

**Comment by nasuccc** [comment] 2023-03-27 21:09
The text in the link is not edited by me, but I encountered these two bugs in the game

**Comment by nasuccc** [comment] 2023-03-31 12:01
![Giant fan](https://user-images.githubusercontent.com/129116646/229114731-625c4e1d-7fbf-476c-b125-55d44d6cf79e.png)

**Comment by nasuccc** [comment] 2023-03-31 12:03
An error occured in SCP - Containment Breach!
Version: 1.3.11
Save compatible version: 1.3.11
Date and time: 31 Mar 2023 at 19:56:10
Total video memory (MB): -1
Available video memory (MB): -208
Global memory status: -1192 MB/-1 MB (-1220268 KB/-1 KB)
Triangles rendered: 46742
Active textures: 255

Error(s):
"1048a" event ***************
SetAnimTime: Entity has no animation

**Comment by theOneTrueFunniBoi** [comment] 2023-09-02 23:52
The game uses the first object assigned to the room (0), as 1048a, the only problem is in the fan room, the fan is object 0, so the game ends up manipulating the fan instead of 1048a. But im not sure how to fix it reliably.

**Comment by ChronoQuote** [comment] 2023-09-03 21:47
These issues are caused by mistakes in `Data\events.ini`. I will try to submit a PR with fixes later.

**Comment by Regalis11** [comment] 2023-09-25 14:26
Fixed in https://github.com/Regalis11/scpcb/pull/253

**Closed by Regalis11** 2023-09-25 14:26 UTC
